# Generated by Django 3.2.8 on 2021-10-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=200),
        ),
    ]
