# Generated by Django 3.2.8 on 2021-10-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_package_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.region'),
            preserve_default=False,
        ),
    ]
